2022-09-16 19:21:35,428 mloop                INFO     M-LOOP version 3.3.1
2022-09-16 19:21:35,429 mloop                DEBUG    M-LOOP Logger configured.
2022-09-16 19:21:35,429 mloop.interfaces     DEBUG    Creating interface.
2022-09-16 19:21:35,502 mloop.controllers    DEBUG    Controller init completed.
2022-09-16 19:21:35,502 mloop.learners.1     DEBUG    Learner init completed.
2022-09-16 19:21:35,503 mloop.learners.1     DEBUG    Random learner init completed.
2022-09-16 19:21:35,503 mloop.learners.2     DEBUG    Learner init completed.
2022-09-16 19:21:35,504 mloop.controllers    INFO     Optimization started.
2022-09-16 19:21:35,505 mloop.learners.1     DEBUG    Starting Random Learner
2022-09-16 19:21:35,506 mloop.interfaces     DEBUG    Entering main loop of interface.
2022-09-16 19:21:35,506 mloop.controllers    DEBUG    ML learner started.
2022-09-16 19:21:35,637 mloop.controllers    DEBUG    Starting training optimization.
2022-09-16 19:21:35,638 mloop.controllers    INFO     Run:1 (training)
2022-09-16 19:21:35,639 mloop.controllers    INFO     params [10.    5.    3.    2.3   2.21  0.15  0.1   0.15  0.1   0.05  0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.  ]
2022-09-16 19:23:36,227 mloop.interfaces     DEBUG    Interface ended
2022-09-16 19:23:36,720 mloop.controllers    ERROR    The interface raised an error with traceback:
  File "C:\Users\SimulationComputer\Anaconda3\lib\site-packages\mloop\interfaces.py", line 133, in run
    cost_dict = self.get_next_cost_dict(params_dict)

  File "c:/Users/SimulationComputer/MLOOP/MLOptimization/EvapML.py", line 52, in get_next_cost_dict
    self.Utility.CheckCompletion()

  File "c:/Users/SimulationComputer/MLOOP/MLOptimization/EvapML.py", line 101, in CheckCompletion
    RunNumber = self.getRunNumber(self.PrevDir)

  File "c:/Users/SimulationComputer/MLOOP/MLOptimization/EvapML.py", line 135, in getRunNumber
    mat = io.loadmat(dir)

  File "C:\Users\SimulationComputer\Anaconda3\lib\site-packages\scipy\io\matlab\mio.py", line 226, in loadmat
    matfile_dict = MR.get_variables(variable_names)

  File "C:\Users\SimulationComputer\Anaconda3\lib\site-packages\scipy\io\matlab\mio5.py", line 312, in get_variables
    hdr, next_position = self.read_var_header()

  File "C:\Users\SimulationComputer\Anaconda3\lib\site-packages\scipy\io\matlab\mio5.py", line 271, in read_var_header
    raise TypeError('Expecting miMATRIX type here, got %d' % mdtype)

2022-09-16 19:23:36,721 mloop.controllers    WARNING  Controller ended due to exception of some kind. Starting shut down...
2022-09-16 19:23:36,721 mloop.controllers    DEBUG    ML learner end set.
2022-09-16 19:23:37,988 mloop.controllers    DEBUG    ML learner joined
2022-09-16 19:23:37,988 mloop.controllers    INFO     Machine learning learner did not provide best and/or all minima.
2022-09-16 19:23:37,989 mloop.controllers    DEBUG    Learner end event set.
2022-09-16 19:23:37,989 mloop.controllers    DEBUG    Interface end event set.
2022-09-16 19:23:38,590 mloop.learners.1     DEBUG    Learner end signal received. Ending
2022-09-16 19:23:39,590 mloop.learners.1     DEBUG    Performing shut down of learner.
2022-09-16 19:23:39,590 mloop.learners.1     DEBUG    Ended Random Learner
2022-09-16 19:23:39,590 mloop.controllers    DEBUG    Learner joined.
2022-09-16 19:23:39,590 mloop.controllers    DEBUG    Interface joined.
2022-09-16 19:23:39,592 mloop.controllers    WARNING  Safely shut down. Below are results found before exception.
2022-09-16 19:23:39,592 mloop.controllers    INFO     Optimization ended because:
2022-09-16 19:23:39,592 mloop.controllers    INFO     	* Error occurred.
2022-09-16 19:23:39,592 mloop.controllers    INFO     Results:
2022-09-16 19:23:39,593 mloop.controllers    INFO     	* Best parameters found:nan
2022-09-16 19:23:39,593 mloop.controllers    INFO     	* Best cost returned:inf +/- nan
2022-09-16 19:23:39,593 mloop.controllers    INFO     	* Best run number:nan
